# Site settings
title: "Xunberg's Tech Blog"
description: "MCP & AI Agent 技术分享"
author: "Xunberg"
email: "burgxun@163.com"
url: "https://xunberg.github.io"
baseurl: ""
last_updated: "2025-07-10"

# Analytics
google_analytics: "G-97GP17YFWB"  # 替换为您的 GA4 测量 ID

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  
# Plugins (GitHub Pages 支持的插件)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: "首页"
    url: "/"
  - title: "MCP 教程"
    url: "/mcp/"
  - title: "AI 编程"
    url: "/agent/"
  - title: "日常分享"
    url: "/daily/"
  - title: "关于"
    url: "/about/"

# Social links
social:
  github: "xunberg"
  csdn: "https://blog.csdn.net/zxlp520"
  juejin: "https://juejin.cn/user/1239904848969895"
  
# Collections
collections:
  posts:
    output: true
  mcp:
    output: true
    permalink: /mcp/:name/
  agent:
    output: true
    permalink: /agent/:name/
  daily:
    output: true
    permalink: /daily/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "mcp"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "agent"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "daily"
    values:
      layout: "post"  
